Remove unnecessary secrets environ variable
mrwadams/attackgen pull request #2
Opened 2023-08-21 15:30 UTC by lbunge

A secrets file was placed in the gitignore file but used as a location for a environ variable causing an error during runtime. Removed it since it wasn't necessary as the openai key was utilized.

2023-08-21 19:24 UTC, mrwadams approved these changes
Good spot, thanks.

2023-08-21 19:31 UTC, mrwadams requested changes
The LANGCHAIN_API_KEY is required for LangSmith logging and some other user feedback related features that I have in mind for a future release. If you can remove that change I'll merge the PR to fix the GitHub URL.

2023-08-21 20:48 UTC, lbunge commented
@mrwadams The LANGCHAIN_API_KEY is referencing a key in a secrets file but I didn't see any documentation on what was needed in said file. Since there is no documentation and the secrets file wasn't created when I cloned the repo, the app threw errors since it couldn't find the variable. Once I removed that variable, it worked as intended.

2023-11-27 09:04 UTC, mrwadams commented
I've now added a `secrets.toml-example` file to the `.streamlit/` directory to show the required format, as well as an extra note in the LangSmith Setup section of the readme file.

2023-11-27 09:04 UTC, closed without merging